#ifndef THING_COL_RENDER
#define THING_COL_RENDER

#include "../map/map.h"

struct thing_column_render_data {
	SDL_Rect* src;
	const SDL_Rect* dest;
	const int* frame_offset;
  struct mapdef* map;

	int thing_sorted_index;
	int screen_column;

  // For rendering
  int start_row, end_row;
  // Used when rendering each col, and calculated once per thing.
  int tex_height;
  int thing_dist_sqrt;
};

void thing_col(const int i, struct thing_column_render_data* td);
void thing_col_1(struct thing_column_render_data* td);
void thing_col_2(struct thing_column_render_data* td);
void thing_col_3(struct thing_column_render_data* td);
void thing_col_4(struct thing_column_render_data* td);
void thing_col_5(struct thing_column_render_data* td);
void thing_col_6(struct thing_column_render_data* td);
void thing_col_7(struct thing_column_render_data* td);
void thing_col_8(struct thing_column_render_data* td);
void thing_col_9(struct thing_column_render_data* td);
void thing_col_10(struct thing_column_render_data* td);
void thing_col_11(struct thing_column_render_data* td);
void thing_col_12(struct thing_column_render_data* td);
void thing_col_13(struct thing_column_render_data* td);
void thing_col_14(struct thing_column_render_data* td);
void thing_col_15(struct thing_column_render_data* td);
void thing_col_16(struct thing_column_render_data* td);
void thing_col_17(struct thing_column_render_data* td);
void thing_col_18(struct thing_column_render_data* td);
void thing_col_19(struct thing_column_render_data* td);
void thing_col_20(struct thing_column_render_data* td);
void thing_col_21(struct thing_column_render_data* td);
void thing_col_22(struct thing_column_render_data* td);
void thing_col_23(struct thing_column_render_data* td);
void thing_col_24(struct thing_column_render_data* td);
void thing_col_25(struct thing_column_render_data* td);
void thing_col_26(struct thing_column_render_data* td);
void thing_col_27(struct thing_column_render_data* td);
void thing_col_28(struct thing_column_render_data* td);
void thing_col_29(struct thing_column_render_data* td);
void thing_col_30(struct thing_column_render_data* td);
void thing_col_31(struct thing_column_render_data* td);
void thing_col_32(struct thing_column_render_data* td);
void thing_col_33(struct thing_column_render_data* td);
void thing_col_34(struct thing_column_render_data* td);
void thing_col_35(struct thing_column_render_data* td);
void thing_col_36(struct thing_column_render_data* td);
void thing_col_37(struct thing_column_render_data* td);
void thing_col_38(struct thing_column_render_data* td);
void thing_col_39(struct thing_column_render_data* td);
void thing_col_40(struct thing_column_render_data* td);
void thing_col_41(struct thing_column_render_data* td);
void thing_col_42(struct thing_column_render_data* td);
void thing_col_43(struct thing_column_render_data* td);
void thing_col_44(struct thing_column_render_data* td);
void thing_col_45(struct thing_column_render_data* td);
void thing_col_46(struct thing_column_render_data* td);
void thing_col_47(struct thing_column_render_data* td);
void thing_col_48(struct thing_column_render_data* td);
void thing_col_49(struct thing_column_render_data* td);
void thing_col_50(struct thing_column_render_data* td);
void thing_col_51(struct thing_column_render_data* td);
void thing_col_52(struct thing_column_render_data* td);
void thing_col_53(struct thing_column_render_data* td);
void thing_col_54(struct thing_column_render_data* td);
void thing_col_55(struct thing_column_render_data* td);
void thing_col_56(struct thing_column_render_data* td);
void thing_col_57(struct thing_column_render_data* td);
void thing_col_58(struct thing_column_render_data* td);
void thing_col_59(struct thing_column_render_data* td);
void thing_col_60(struct thing_column_render_data* td);
void thing_col_61(struct thing_column_render_data* td);
void thing_col_62(struct thing_column_render_data* td);
void thing_col_63(struct thing_column_render_data* td);
void thing_col_64(struct thing_column_render_data* td);
void thing_col_65(struct thing_column_render_data* td);
void thing_col_66(struct thing_column_render_data* td);
void thing_col_67(struct thing_column_render_data* td);
void thing_col_68(struct thing_column_render_data* td);
void thing_col_69(struct thing_column_render_data* td);
void thing_col_70(struct thing_column_render_data* td);
void thing_col_71(struct thing_column_render_data* td);
void thing_col_72(struct thing_column_render_data* td);
void thing_col_73(struct thing_column_render_data* td);
void thing_col_74(struct thing_column_render_data* td);
void thing_col_75(struct thing_column_render_data* td);
void thing_col_76(struct thing_column_render_data* td);
void thing_col_77(struct thing_column_render_data* td);
void thing_col_78(struct thing_column_render_data* td);
void thing_col_79(struct thing_column_render_data* td);
void thing_col_80(struct thing_column_render_data* td);
void thing_col_81(struct thing_column_render_data* td);
void thing_col_82(struct thing_column_render_data* td);
void thing_col_83(struct thing_column_render_data* td);
void thing_col_84(struct thing_column_render_data* td);
void thing_col_85(struct thing_column_render_data* td);
void thing_col_86(struct thing_column_render_data* td);
void thing_col_87(struct thing_column_render_data* td);
void thing_col_88(struct thing_column_render_data* td);
void thing_col_89(struct thing_column_render_data* td);
void thing_col_90(struct thing_column_render_data* td);
void thing_col_91(struct thing_column_render_data* td);
void thing_col_92(struct thing_column_render_data* td);
void thing_col_93(struct thing_column_render_data* td);
void thing_col_94(struct thing_column_render_data* td);
void thing_col_95(struct thing_column_render_data* td);
void thing_col_96(struct thing_column_render_data* td);
void thing_col_97(struct thing_column_render_data* td);
void thing_col_98(struct thing_column_render_data* td);
void thing_col_99(struct thing_column_render_data* td);
void thing_col_100(struct thing_column_render_data* td);
void thing_col_101(struct thing_column_render_data* td);
void thing_col_102(struct thing_column_render_data* td);
void thing_col_103(struct thing_column_render_data* td);
void thing_col_104(struct thing_column_render_data* td);
void thing_col_105(struct thing_column_render_data* td);
void thing_col_106(struct thing_column_render_data* td);
void thing_col_107(struct thing_column_render_data* td);
void thing_col_108(struct thing_column_render_data* td);
void thing_col_109(struct thing_column_render_data* td);
void thing_col_110(struct thing_column_render_data* td);
void thing_col_111(struct thing_column_render_data* td);
void thing_col_112(struct thing_column_render_data* td);
void thing_col_113(struct thing_column_render_data* td);
void thing_col_114(struct thing_column_render_data* td);
void thing_col_115(struct thing_column_render_data* td);
void thing_col_116(struct thing_column_render_data* td);
void thing_col_117(struct thing_column_render_data* td);
void thing_col_118(struct thing_column_render_data* td);
void thing_col_119(struct thing_column_render_data* td);
void thing_col_120(struct thing_column_render_data* td);
void thing_col_121(struct thing_column_render_data* td);
void thing_col_122(struct thing_column_render_data* td);
void thing_col_123(struct thing_column_render_data* td);
void thing_col_124(struct thing_column_render_data* td);
void thing_col_125(struct thing_column_render_data* td);
void thing_col_126(struct thing_column_render_data* td);
void thing_col_127(struct thing_column_render_data* td);
void thing_col_128(struct thing_column_render_data* td);
void thing_col_129(struct thing_column_render_data* td);
void thing_col_130(struct thing_column_render_data* td);
void thing_col_131(struct thing_column_render_data* td);
void thing_col_132(struct thing_column_render_data* td);
void thing_col_133(struct thing_column_render_data* td);
void thing_col_134(struct thing_column_render_data* td);
void thing_col_135(struct thing_column_render_data* td);
void thing_col_136(struct thing_column_render_data* td);
void thing_col_137(struct thing_column_render_data* td);
void thing_col_138(struct thing_column_render_data* td);
void thing_col_139(struct thing_column_render_data* td);
void thing_col_140(struct thing_column_render_data* td);
void thing_col_141(struct thing_column_render_data* td);
void thing_col_142(struct thing_column_render_data* td);
void thing_col_143(struct thing_column_render_data* td);
void thing_col_144(struct thing_column_render_data* td);
void thing_col_145(struct thing_column_render_data* td);
void thing_col_146(struct thing_column_render_data* td);
void thing_col_147(struct thing_column_render_data* td);
void thing_col_148(struct thing_column_render_data* td);
void thing_col_149(struct thing_column_render_data* td);
void thing_col_150(struct thing_column_render_data* td);
void thing_col_151(struct thing_column_render_data* td);
void thing_col_152(struct thing_column_render_data* td);
void thing_col_153(struct thing_column_render_data* td);
void thing_col_154(struct thing_column_render_data* td);
void thing_col_155(struct thing_column_render_data* td);
void thing_col_156(struct thing_column_render_data* td);
void thing_col_157(struct thing_column_render_data* td);
void thing_col_158(struct thing_column_render_data* td);
void thing_col_159(struct thing_column_render_data* td);
void thing_col_160(struct thing_column_render_data* td);
void thing_col_161(struct thing_column_render_data* td);
void thing_col_162(struct thing_column_render_data* td);
void thing_col_163(struct thing_column_render_data* td);
void thing_col_164(struct thing_column_render_data* td);
void thing_col_165(struct thing_column_render_data* td);
void thing_col_166(struct thing_column_render_data* td);
void thing_col_167(struct thing_column_render_data* td);
void thing_col_168(struct thing_column_render_data* td);
void thing_col_169(struct thing_column_render_data* td);
void thing_col_170(struct thing_column_render_data* td);
void thing_col_171(struct thing_column_render_data* td);
void thing_col_172(struct thing_column_render_data* td);
void thing_col_173(struct thing_column_render_data* td);
void thing_col_174(struct thing_column_render_data* td);
void thing_col_175(struct thing_column_render_data* td);
void thing_col_176(struct thing_column_render_data* td);
void thing_col_177(struct thing_column_render_data* td);
void thing_col_178(struct thing_column_render_data* td);
void thing_col_179(struct thing_column_render_data* td);
void thing_col_180(struct thing_column_render_data* td);
void thing_col_181(struct thing_column_render_data* td);
void thing_col_182(struct thing_column_render_data* td);
void thing_col_183(struct thing_column_render_data* td);
void thing_col_184(struct thing_column_render_data* td);
void thing_col_185(struct thing_column_render_data* td);
void thing_col_186(struct thing_column_render_data* td);
void thing_col_187(struct thing_column_render_data* td);
void thing_col_188(struct thing_column_render_data* td);
void thing_col_189(struct thing_column_render_data* td);
void thing_col_190(struct thing_column_render_data* td);
void thing_col_191(struct thing_column_render_data* td);
void thing_col_192(struct thing_column_render_data* td);
void thing_col_193(struct thing_column_render_data* td);
void thing_col_194(struct thing_column_render_data* td);
void thing_col_195(struct thing_column_render_data* td);
void thing_col_196(struct thing_column_render_data* td);
void thing_col_197(struct thing_column_render_data* td);
void thing_col_198(struct thing_column_render_data* td);
void thing_col_199(struct thing_column_render_data* td);
void thing_col_200(struct thing_column_render_data* td);

#endif
